

module.exports = {
  ESTADOCONFIRMADO:1,
  ESTADOACTIVO:2,
  ESTADORETIROPARCIAL:4,
  ESTADOPERDIDO:6,
  ESTADOIMPEDIMENTOACADEMICO:8  ,
ESTADONIVELACIONAPROBACION:9  ,
REPETICIONESaSIGNATURAS:2,
EQUIVALENCIAPERDIDAaSIGNATURA:"R",
  };