

module.exports = {
  ESTADOCONFIRMADO:1,
  ESTADOACTIVO:2,
  ESTADOINACTIVO:3,
  ESTADORETIROPARCIAL:4,
  ESTADORETIRODEFINITIVO:5,
  ESTADOPERDIDO:6,
  ESTADOANULACION:7,
ESTADOIMPEDIMENTOACADEMICO:8  ,
ESTADONIVELACIONAPROBACION:9  ,
REPETICIONESaSIGNATURAS:2,
EQUIVALENCIAPERDIDAaSIGNATURA:"R",
  };