module.exports = {
    "director": "COORDINADOR/A",
    "secretaria": "SECRETARIA ACADÉMICA",
    "decano": "DECANO",
    "tokenfirmaEc":  "6a2a210a80e539f8b175eabcbdeb0d8127b90615c2c5b3062593c151269a0ff8",
    "urldocumentosfirmaEc": "http://apifirmaec.espoch.edu.ec/servicio/documentos",
    "urlCorreo": "https://emailrelay.espoch.edu.ec/WebCorreoInstitucional/ServiciosCorreos/EnviarCorreo",
    "urldependenciadadoid": "https://swtalentohumano.espoch.edu.ec/hojavidaAD/wshojavida/dependencia/",
    "urldominiosistema": "https://can.espoch.edu.ec",
    "clavecorreoinst": "SAIN",
    "diasvigenciasolicitud": 7,
    "urlcentralactualizaradmision": "https://centralizada2.espoch.edu.ec/rutadinardap/obtenerpersona/",
    "urlhash": "https://swtalentohumano.espoch.edu.ec/hojavidaAD/wshojavida/obtenerhashPOST",
    "urlhashverificar": "https://swtalentohumano.espoch.edu.ec/hojavidaAD/wshojavida/respuestadecontrasenia",
    "urlcentralobtenerpersona": "https://centralizada2.espoch.edu.ec/rutadinardap/obtenerpersona/",
    "rutaCertificadoKey":"../Certificados/STAR_espoch_edu_ec.key",
    "rutaCertificadoCrt1":"../Certificados/STAR_espoch_edu_ec.crt",
    "rutaCertificadoCrt2":"../Certificados/STAR_espoch_edu_ec.crt",
};